config/routes.rb
Projectshow::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  resources :attachments

  resources :projects do
    collection do
      get 'attachment'
    end
  end
  

  get "home/index"
  get "home/about"
  get "home/about_scs"
  devise_for :users
  
  

  root 'home#about_scs'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard 
      can :manage, :all 
    elsif user
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard 
      can [:index,:show,:update], Project ,user_id: user.id
      can [:index,:show,:update], User ,id: user.id
    end
  end
end

app/models/attachment.rb
#encoding : utf-8
class Attachment < ActiveRecord::Base
  rails_admin do
    field :title do
      label '附件标题'
    end
    field :content, :ck_editor do
      label '附件内容'
    end
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/project.rb
# encoding : utf-8
class Project < ActiveRecord::Base
  validates :description, :length => { :maximum => 200 }
  validates :user_id, presence: true
    
  belongs_to :user
  mount_uploader :video, FileUploader
  mount_uploader :file, FileUploader
    
  rails_admin do        
    field :name
    field :description, :text
    field :declaration, :ck_editor
    field :assignment_book, :ck_editor
    field :phase_check, :ck_editor
    field :experience, :ck_editor
    field :achievement, :ck_editor
    field :video, :carrierwave
    field :attachment, :ck_editor do
      label '项目附件'
    end
    field :user_id, :enum do
      label '项目团队email'
      enum do
        User.all.map{ |user| [user.email,user.id]}
      end
    end
  end
end

app/models/setting.rb
# encoding : utf-8
require 'yaml'
class Setting
    
  def self.getYaml(filepath="config/settings.yml")
    YAML.load_file(filepath)
  end
end

app/models/user.rb
# encoding : utf-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  has_one :project
  
  class << self
     def current_user=(user)
       Thread.current[:current_user] = user
     end

     def current_user
       Thread.current[:current_user]
     end
   end
   
   def admin?
     self.email.to_s  == Setting.getYaml["admin_email"].to_s
   end
   
  rails_admin do
    #visible false
    label_plural '管理员管理'
    field :email
    field :password
    field :password_confirmation do
      label '确认密码'
    end
    # visible do
    #   bindings[:controller].current_user.email.to_s == Setting.getYaml["admin_email"].to_s
    # end
  end
end

app/controllers/application_controller.rb
#encoding : utf-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_current_user

  def set_current_user
    User.current_user = current_user
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attachment }
      else
        format.html { render action: 'new' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:user_id)
    end
end

app/controllers/home_controller.rb
#encoding : utf-8
class HomeController < ApplicationController
  def index
  	@projects = Project.all
  end

  def about
  	
  end

  def about_scs
  	
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end
  
  def attachment
    @projects = Project.where("file is NOT NULL")
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/attachments/_file_show.html.erb
<object id="WebOffice" height="768" width="100%" 
style="LEFT: 0px; TOP: 0px" classid="clsid:E77E049B-23FC-4DB8-B756-60529A35FAD5" codebase="WebOffice1.ocx#version=6,0,4,0">
<param name="_ExtentX" value="6350">
<param name="_ExtentY" value="6350">
</object>



<SCRIPT language="javascript" event="NotifyCtrlReady" for="WebOffice" >
/****************************************************
*
*	在装载完Weboffice(执行<object>...</object>)
*	控件后执行 "WebOffice1_NotifyCtrlReady"方法
*
****************************************************/
WebOffice1_NotifyCtrlReady();
</SCRIPT>

<script type="text/javascript">
function WebOffice1_NotifyCtrlReady() {
document.all.WebOffice1.LoadOriginalFile("<%=@attachment.file.url %>", "doc");
}
</script>

app/views/attachments/_filelist.html.erb
<table class="table table-hover .table-bordered">
	<!--<thead>
		<tr>
<<<<<<< HEAD
			<th>文件</th>
			
=======
			<th></th>
			<!--
>>>>>>> 77367d00df34f3dfdef2f7fb503f4ad20bbecb64
			<th>上传时间</th>
			<th>下载</th>
		
		</tr>
	</thead>-->
  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
		  <td><a href="/attachments/<%=attachment.id%>" class="link file_link"><%= attachment.title%></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<div class="container-fluid content-over">
  <div class="row-fluid">
    <div class="span12">

      <div class="row-fluid" id="container">
        <div class="span2">
          <%= render "projects/index_nav" %>
        </div>
        <div class="span10 well alpha">
  			<div class="span12">
			<h3>

			管理文件

			</h3>
			<%= render "filelist"%>
		</div>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
	$("#show_nav").pin({
      containerSelector: "#container"
	});
</script>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<div class="container-fluid content-over">
  <div class="row-fluid">
    <div class="span12">

      <div class="row-fluid" id="container">
        <div class="span2">
          <%= render "projects/index_nav" %>
        </div>
        <div class="span10 well alpha">
        <%= raw @attachment.content %>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  $("#show_nav").pin({
      containerSelector: "#container"
  });
</script>

app/views/home/_scs_content.html.erb
<div><div class="pageright">
<div class="pagerightcontent"><div class="content">
<p style="TEXT-INDENT: 2em"><font size="4" face="宋体">西南石油大学计算机专业创建于1984年，当年开始专科招生，1986年开始本科招生, 
1997年开始硕士研究生招生。1995年成立计算机科学系，2000年成立计算机科学学院。 </font></p>
<p style="TEXT-INDENT: 2em"><font size="4" face="宋体">学院设有计算机科学与技术、软件工程、网络工程、物联网工程共4个本科专业，并建有计算机科学与技术、软件工程两个硕士学位授权一级学科点、石油工程计算技术硕士点与博士点、以及计算机应用、软件工程等两个工程硕士领域，建有“石油工程计算机模拟技术”四川省高校重点实验室、“数据工程与数据分析”中美高校联合实验室、“面向对象数据库”校企联合实验室、SAP联合实验室等科研机构。 
</font></p>
<p style="TEXT-INDENT: 2em"><font size="4" face="宋体">学院现有教职工90余人，其中专职教师近80人，包括四川省“百人计划”首批入选者1人，博士生导师1人，教授10人，副教授13人。学院现有全日制在校学生1300余人，其中博、硕士研究生近100人，本科生1200余人。三十年来，学院科学研究硕果累累，在计算机模拟与仿真、数据挖掘与数据库开发、嵌入式系统、企业信息化建设、模式识别、人工智能与专家系统、地理信息系统、虚拟现实等多个稳定研究领域取得了重大研究成果和应用成果，其中石油工程钻井模拟培训装置成果已达到国内领先、国际一流水平。 
2006年以来，学院科学研究发展迅速，承担了国家重大专项子项目、国家自然科学基金等多项高水平国家项目，纵横向科研经费近5年突破3000万元。学院教师发表学术论文近350篇，其中被SCI/EI检索收录200多篇，获得专利及软件著作权50余项。 
</font></p>
<p style="TEXT-INDENT: 2em"><font size="4" face="宋体">近年来，学院在本科教学、研究生教学等方面取得了显著成果，人才培养质量大幅度提高。学院除建有四个本科专业外，还负责承担全校性计算机公共基础课程、以及部分院系、部分专业的相关专业基础及专业课程教学工作，曾获得四川省教学成果奖1项及四川省优秀电教科研成果奖1项，另有2门课程被评为四川省精品课程，计算机科学与技术专业则于2008年被评为四川省特色专业。学院积累了丰富的人才培养经验，建立了较为完整的学科专业结构和人才培养体系，先后为社会输送了3000余名计算机相关领域的专业技术人才，为我国油田和地方经济发展做出了一定的贡献。学院拥有良好的办学条件和育人环境，建有多个校内、校外学生实践实训基地，教学及科研实验室面积约4000平方米，拥有先进的洞穴式计算机虚拟现实系统及80余套高性能图形工作站、400余台微机、各类教学实验设备等，总资产达1000余万元。学院设有5个教研室、1个综合教学实验中心和1个学生实训中心，目前已成为西南地区培养计算机应用、软件开发和网络工程等IT领域应用型高级技术人才的重要基地。 
</font></p>
<p style="TEXT-INDENT: 2em"><font size="4" face="宋体">学院不断加强与国内外知名高校进行学术交流与合作。近三年来，已邀请30余位国内外知名专家来校进行交流访问，并选派优秀教师赴国内外知名大学进修。学院与肯塔基大学合作，成功举办了两次大型国际学术会议，提高了学院在国内的学术影响力。学院积极探索校企联合办学、抵近市场培养人才的新型模式，与国内众多知名IT企业建有“3+1”及“2+1+1”的深度合作关系，长期执行人才定制培养计划，从而开辟了广泛的就业渠道，建立了稳定的就业基地。在保持较高就业率的同时，还保证了良好的学生就业质量，绝大多数毕业生就业地点分布在北京、上海、重庆、成都、大连、广州等中心城市，历年的毕业生质量均得到了用人单位普遍好评。学院还注重外语应用能力培养，并与部分外资企业建立了人才输送绿色通道，使优秀毕业生有机会直接赴日本、印度、欧洲等海外地区工作。 
</font></p>
<p style="TEXT-INDENT: 2em"><font size="4" face="宋体">学院以培养创新性人才和复合型人才为目标，积极创造条件与机会，鼓励学生参与社会实践、素质拓展、课外科技及学术研究等活动。依托校内大学生实训中心，学院成立了多个学生科技团队，有序组织学生对外承接外包项目开发、参加各级课外科技竞赛活动等，近几年取得了20余项国家级及省级以上的奖励，获得项目经费总额达60余万元，并帮助部分学生走上了创业成才的道路，也受到了各兄弟院校的瞩目。 &nbsp;</font></p></div></div></div></div>

app/views/home/about.html.erb
<div class="container-fluid content-over">
  <div class="row-fluid">
    <div class="span12">

      <div class="row-fluid" id="container">
        <div class="span2">
          <%= render "projects/index_nav" %>
        </div>
        <div class="span10 well alpha">
<div class="span12">
			<h3>
				“本科教学工程”
			</h3>
			<p>
				<em>Git</em>是一个分布式的版本控制系统，最初由<strong>Linus Torvalds</strong>编写，用作Linux内核代码的管理。在推出后，Git在其它项目中也取得了很大成功，尤其是在Ruby社区中。
			</p> <address> <strong>Twitter, Inc.</strong><br /> 795 Folsom Ave, Suite 600<br /> San Francisco, CA 94107<br /> <abbr title="Phone">P:</abbr> (123) 456-7890</address>
		</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/about_scs.html.erb
<div class="container-fluid content-over">
  <div class="row-fluid">
    <div class="span12">

      <div class="row-fluid" id="container">
        <div class="span2">
          <%= render "projects/index_nav" %>
        </div>
        <div class="span10 well alpha">
  			<div class="span12">
			<h3>
			计算机科学学院简介
			</h3>
			<%= render "home/scs_content" %>
		</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid content-over">
	<div class="row-fluid">
		<div class="span12 ">
			<div style="margin-bottom:36px;">
				<h2 style="color:#fefefe;">
					计算机科学学院"本科教学质量工程"
				</h2>
				<p style="color:#ddd;font-size:16px;margin-top:20px;margin-bottom:20px;">
					计算机科学学院学院办学始于1984年，主要面向我国快速发展的信息产业领域培养工程型与应用型技术人才，现已拥有完整的学科专业结构和人才培养体系，设有计算机科学与技术、软件工程、网络工程、物联网工程共4个本科专业，并建有计算机科学与技术、软件工程两个硕士学位授权一级学科点、石油工程计算技术硕士点与博士点、以及计算机应用、软件工程等两个工程硕士领域，目前在校本科生及博士、硕士研究生总数近1300人。
				</p>
				<p>
					<!--
					<a class="btn btn-success btn-large" href="/home/about">关于“本科教学工程” »</a>
				-->
					<a class="btn btn-info btn-large" href="/home/about_scs">学院简介 »</a>
					<a class="btn btn-large  btn-success"  href="/admin">管理入口</a>
				</p>
			</div>
			<h3 style="color:#eee;margin-bottom:16px;">
					项目展示
			</h3>
			<%= render "projects/projects_list" %>
		</div>
	</div>
</div>

app/views/layouts/_projects_nav.html.erb
<div class="accordion" id="projects_nav" >

						<div class="accordion-group">
							<div class="accordion-heading">
								 <a class="accordion-toggle  unfold"  href="#">
								 	快速通道
								 </a>
							</div>
						</div>
						<div class="accordion-group">
							<div class="accordion-heading">
								 <a class="accordion-toggle  unfold" data-toggle="collapse" data-parent="#projects_nav" href="#accordion-element-355347">
								 	计科院
								 </a>
							</div>
							<div id="accordion-element-355347" class="accordion-body collapse">
								<div class="accordion-inner">
									<a href="#" class="projects_link">微大学</a>
									<a href="#" class="projects_link">功能块...</a>
									<a href="#" class="projects_link">功能块...</a>
									<a href="#" class="projects_link">功能块...</a>
									<a href="#" class="projects_link">功能块...</a>
								</div>
							</div>
						</div>
						<div class="accordion-group">
							<div class="accordion-heading">
								 <a class="accordion-toggle unfold" data-toggle="collapse" data-parent="#projects_nav" href="#accordion-element-369432">石工院</a>
							</div>
							<div id="accordion-element-369432" class="accordion-body collapse">
								<div class="accordion-inner">
									功能块...
								</div>
							</div>
						</div>
					</div>
<script type="text/javascript">
						$("#projects_nav").pin({
      containerSelector: "#container"
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Projectshow</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" =>
	true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" =>
	true %>
	<%= csrf_meta_tags %></head>
<body>
	<div class="background-base">
		<img alt="" src="<%= image_url 'desk/swpuscs1.jpg' %>" class="background-img" /></div>

	<div class="span12">
		<h2 style="color:#fefefe;padding-bottom:8px;padding-top:7px;">计算机科学学院"本科教学质量工程"</h2>
	</div>

	<%= yield %>
<script type="text/javascript">
$("#show_nav").pin({
      containerSelector: "#container"
  });
  </script>
	
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectshow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="background-base">
<img alt="" src="<%= image_url 'desk/swpuscs1.jpg' %>
			" class="background-img" />
</div>
				<%= yield %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectshow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="background-base">
<img alt="" src="<%= image_url 'desk/swpuscs1.jpg' %>
			" class="background-img" />
</div>
				<%= yield %>
</body>
</html>

app/views/projects/_filelist.html.erb
<table class="table table-hover .table-bordered">
	<!--<thead>
		<tr>
			<th>文件</th>
			
				<th>上传时间</th>
				<th>下载</th>
				
			</tr>
		</thead>-->
		<tbody>
			<% unless @projects.nil?%>
			<% @projects.each do |project| %>
			<tr>
				<td><a href="<%= project.file.url%>" class="link file_link"><%=File.basename project.file.url%></a></td>
			</tr>
			<% end %>
			<% end %>
		</tbody>
	</table>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_index_nav.html.erb
<div class="alpha show_nav" id="show_nav">
<ul class="nav nav-list left-nav-over" >
				<%= render "projects/left_nav" %>
			</ul>
</div>

app/views/projects/_left_nav.html.erb
<li class="nav-header">站内链接</li>
<!--
<li>
<a href="/home/index">首页</a>
</li>
-->
<li>
	<a href="/home/about_scs">计科院简介</a>
</li>
<li>
	<a href="/projects">项目列表</a>
</li>

<li>
	<a href="/attachments">管理文件</a>
</li>
<li>

	<a href="/admin">管理入口</a>
</li>

app/views/projects/_projects_list.html.erb
<% index=0 %>
<ul class="thumbnails">
	<% @projects.each do |project| %>
	<li class="span4 radius alpha">
		<div class="thumbnail">
			<div class="caption">
				<h3 class="projects_list_title">
					<%=link_to project.name,"/projects/#{project.id}",:class=>"link" %></h3>
				<p class="projects_list_brief">
					<%= project.description %>
				</p>
			</div>
		</div>
	</li>
	<% index=index+1 %>
	<% if (index%3)==0 %></ul>
<ul class="thumbnails">
	<% end %>
	<% end %></ul>

app/views/projects/_show_content.html.erb
<h2><%=raw  @project.name %></h2>

<div class="module" id="description" style="display:block;">
<legend>项目简介</legend>
<p><%=raw @project.description %></p>
</div>

<div class="module" id="declaration">
<legend>申报书</legend>
<p><%=raw @project.declaration %></p>
</div>

<div class="module" id="assignment_book">
<legend >任务书</legend>
<p><%=raw @project.assignment_book %></p>
</div>

<div class="module" id="phase_check">
<legend >阶段检查</legend>
<p><%=raw @project.phase_check %></p>
</div>

<div class="module" id="experience">
<legend >经验交流</legend>
<p><%=raw @project.experience %></p>
</div>

<div class="module" id="achievement">
<legend >成果展示</legend>
<p><%=raw @project.achievement %></p>
</div>

<div class="module" id="projectsfile">
<legend >项目附件</legend>
<p><%=raw @project.attachment %></p>
</div>


<% if @project.video? %>
<div class="module" id="video">
<legend >项目视频</legend>
<video width="100%" height="50%"  src="<%= @project.video.url%>" controls="controls">
您的浏览器不支持 video 标签。
</video>
</div>

<div class="module" id="attachment">
<legend >成果展示</legend>
<p><%=raw @project.attachment %></p>
</div>
<% end %>

app/views/projects/_show_nav.html.erb
<div class="alpha show_nav " id="show_nav">
	<ul class="nav nav-list left-nav-over" >
		<li class="nav-header">项目导航</li>
		<li>
			<a id="description" class="nav_button">项目简介</a>
		</li>
		<li>
			<a id="declaration" class="nav_button">申请书</a>
		</li>
		<li>
			<a  id="assignment_book" class="nav_button">任务书</a>
		</li>
		<li>
			<a id="phase_check" class="nav_button">阶段检查</a>
		</li>
		<li>
			<a  id="experience" class="nav_button">经验交流</a>
		</li>
		<li>
			<a id="achievement" class="nav_button">成果展示</a>
		</li>
		<li>
			<a  id="projectsfile" class="nav_button">项目附件</a>
		</li>
		<% if @project.video? %>
		<li>
			<a  id="video" class="nav_button">视频展示</a>
		</li>
		<% end %>
		<li>
			<a  id="all" class="nav_button">显示所有</a>
		</li>
		<li>
			<a href="/projects">返回列表</a>
		</li>
	</ul>
</div>

app/views/projects/edit.html.erb
<div class="span10">
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
</div>

app/views/projects/new.html.erb
<div class="span10">
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>